### ISSUE TITLE
Doesn't work, use: /rsjrny/Garmin-Connect-Export ?

### ISSUE THREAD

**Issue by jedie** [pe-st/garmin-connect-export#24]
Currently this project doesn't work, isn't it?

I found a working garmin connect export here: https://github.com/rsjrny/Garmin-Connect-Export

I think it makes sense to close this project and contribute to: https://github.com/rsjrny/Garmin-Connect-Export

**Comment by pe-st** [comment]
Hello @jedie 
What doesn't work in this project, can you be more specific? Or can you set the loglevel to verbose (`-v`) and attach the logfile?
From a quick glance at @rsjrny's project it's a refactoring of a copy of @moderation's project, without even having properly forked it. What it lacks (or what I like in my project) is the configurability of the CSV output.

**Comment by jedie** [comment]
The login doesn't work. Sorry i removed everything to use your project and switched to rsjrny/Garmin-Connect-Export ... So i can't easy add a logfile here.

The other project works with python 3 and it also has the ability to skip existing files. (I don't know if this project can do the same.)

**Comment by bartskowron** [comment]
This is somehow true. There are plenty of forks and each of them has some tiny usable features.
AFAIR I also had issues with using this project. I wanted to add another feature and decided to follow the @moderation's project as it looks the most stable.

> From a quick glance at @rsjrny's project it's a refactoring of a copy of @moderation's project, without even having properly forked it. 

If we want to talk about quality...I saw the last PR #23 that was approved and there were plenty of comments that should be made and fixed (that I didn't have chance to state due to quick closing PR process). However, I believe 99% of so-called Garmin Exporter are only interested in exporting files and nothing else, so keeping like 4-5 forks that non of them seems to work well doesn't look like the best possible option..

**Comment by bartskowron** [comment]
> @bartskowron The --start_activity_no feature added in PR #23 works for me. If you're having a problem with that feature, you may want to open a new issue. I believe that PR was closed because the feature was successfully added and I don’t think it’s usual to keep PRs open for a comment period after the code was merged. Perhaps I’m misunderstanding what you are saying about quality.

I was talking about a legacy of code, not feature itself. I didn't have enough time to do a review before code was merged. But it's ok. This is just an utility and there is no need to keep a regime.

> This fork is actively maintained and developed and, AFAIK, all features are working. Any issues that have come up have been promptly fixed and most of those issues were because Garmin changed things at the back end. I definitely do not share the opinion that this project should be closed.

I never intended to agree about closing especially this particular one. All I wanted to say that there are few forks, some of them not maintained regularly that break the login API usually. Some with different focus but all of them tiny and fragile due to lack of community. I'm sure it would be a way easier to maintain and develop the project while all forks would be merged together.

**Comment by pe-st** [comment]
I'm not happy about the many forks either. Maybe once my fork is migrated to Python 3 (see below) we could talk about consolidating the forks...

> The login doesn't work. Sorry i removed everything to use your project and switched to rsjrny/Garmin-Connect-Export ... So i can't easy add a logfile here.

@jedie : It happens from time to time that the login doesn't work anymore because of changes with the Garmin site. IMHO I was the first to fix the login in April 2019 when Garmin changed their site (again). Two days later @moderation fixed his fork, which served as base for @rsjrny's fork. So basically the login code is the same in all these projects, and for me it still works.

> The other project works with python 3 and it also has the ability to skip existing files. (I don't know if this project can do the same.)

As @jamorris confirmed above out the new feature to skip records works.

And as for python 3: this is planned (as python 2 support ends at december 2019), but will take some time. I maintain this project in my spare time and will surely find some time in the coming months; I'd like to make the code compatible with both python 2 and 3 (following the advices in https://python-future.org/compatible_idioms.html). But I'm happy to accept pull requests if somebody else wants to go forward.

@bartskowron I'm also happy if someone wants to open a discussion PR for improving the code quality; Python is not my primary language, so I'm ready to learn from more knowledgable developers.

**Comment by bartskowron** [comment]
> @bartskowron I'm also happy if someone wants to open a discussion PR for improving the code quality; Python is not my primary language, so I'm ready to learn from more knowledgable developers.

I think this could be conducted with the Python 3 migration. Either as a main part or code review.

**Comment by moderation** [comment]
FYI my fork only works with Python 3. Python 2 in theory is deprecated and unsupported in 4 months and 4 days - https://pythonclock.org.

**Comment by jedie** [comment]
> @jedie : It happens from time to time that the login doesn't work anymore because of changes with the Garmin site. IMHO I was the first to fix the login in April 2019 when Garmin changed their site (again). Two days later @moderation fixed his fork, which served as base for @rsjrny's fork. So basically the login code is the same in all these projects, and for me it still works.

This is the problem of many forks.

I think a central **exporter** project would be good. But it really should be **only** an exporter. The data should not be interpreted or evaluated in any way. This can be done by separate projects using the exporter.

I think https://github.com/rsjrny/Garmin-Connect-Export/ would be a good basis.

**Comment by telemaxx** [comment]
i have started to migrate the script to python3:
https://github.com/telemaxx/garmin-connect-export-pest/tree/Python3

i did some short tests with python3 and pypy2. looks good.

need some more tests.

**Comment by telemaxx** [comment]
after some more tests, i send a PR to this repro

**Comment by jedie** [comment]
I tested current master from here https://github.com/pe-st/garmin-connect-export and it works fine! Great!
