### ISSUE TITLE
Detaching from the upstream repository

### ISSUE THREAD

**Issue by bxsx** [pe-st/garmin-connect-export#53]
It's been a long history for forking `garmin-connect-export`. We can see it at here: https://github.com/pe-st/garmin-connect-export/network/members

Unfortunately, it seems like @kjkjava (owner of the upstream) is not interested in the project anymore. Since 2018, we have been expecting at least a comment on the PR42@upstream https://github.com/kjkjava/garmin-connect-export/pull/42
No luck. As for now, we are 271 commits ahead.

As this is the most active repository of the project, I'm suggesting to **detach** from the upstream.

Pros:
* GitHub will count activity in the repository (such as commits)
* Users will stop to be confused about multiple forks and which project is actually active
* Contributors will know where to send PRs instead of randomly sending them around forks
Cons:
* Breaking a great history of forking the project ;)

Here are some docs regarding the issue:
* General information: https://github.community/t/getting-all-your-commits-in-your-contributions-graph/10186
* Detaching procedure: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by pe-st** [comment]
I agree that it is long due to detach from @kjkjava's repo. The [procedure](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork) basically is:

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support or GitHub Premium Support. If the fork has forks of its own, let GitHub Support know if the forks should move with your repository into a new network or remain in the current network. 

As there are about 30 forks of my own repo, I'll hope I get some feedback of the owners listed below if they want to "move with my (@pe-st) repository or remain in the network of kjkjava".

So I'll wait until end of January. I'll assume that repo owners listed below want to keep the "fork" relation with my (@pe-st) repo unless they react with an email, a comment or a 👎🏽 (-1) emoji to this message.

**If you want to stay a fork of @kjkjava then please react with a 👎🏽 until January 31, if you want to move with this repo and stay a fork of @pe-st please react with a 👍🏽** 

So here's the list of the forks of my fork; I hope everybody gets notified when mentioned here:

@alcantarar @amitra @andyakrn @benhollomon @chrismetcalf @chs8691 @rb83421 @cfculhane @cristian5th @gmajor67 @hrpomrx @ibury08 @jedie @jkall @jonasbg @jtorrex @lindback @mdrumond @meinert @mipapo @realflunschi @reto @roballey @rsjrny @storopoli @telemaxx @thetiger7 @wscott1541 @zeair

**Comment by roballey** [comment]
* 👍🏽*

**Comment by cfculhane** [comment]
Great idea, thanks for pursuing this!

**Comment by rb83421** [comment]
👍🏽

Op zo 3 jan. 2021 11:43 schreef Peter Steiner <notifications@github.com>:

**Comment by jkall** [comment]
👍🏽

⁣

Den 3 jan. 2021 11:43, kI 11:43, Peter Steiner <notifications@github.com> skrev:

**Comment by bxsx** [comment]
Looks like we can move forward. Did you get any disagreement in private, @pe-st ?

**Comment by pe-st** [comment]
The repo has been detached on 2021-02-03

**Comment by kjkjava** [comment]
@pe-st Thank you for taking ownership of this project. As you (and all other contributors) have noticed, I am currently unable to keep up with this project. I feel bad for not at least responding to issues/PRs, but I've been pulled in many directions with work and other various projects.

I'm happy to add others to my repo to maintain it, but it sounds like all I need to do at this point is point others to your fork, right?

I'm glad Garmin finally added the ability to export data in bulk, but I will have to give your updated tool a try soon for the added features!
